query Group ($id: ID!) {
  Group(id: $id) {
    id
    name
    users {
      id
      name
      image
      milesThisWeek
      milesThisMonth
    }
    donations {
      id
      amount
      user {
        id
      }
    }
  }
}
