query UserOwnedGroups {
  user {
    id
    groups {
      id
      name
      users {
        id
      }
    }
    ownedGroups {
      id
      name
      invitations {
        id
        email
        name
      }
    }
  }
}
